### ISSUE TITLE
website photos update - January 7th, 2019

### ISSUE THREAD

**Issue by JohnnyBigos** [cbkrol/Cedar-Ridge-High-School-Website#140]
Hi,

We are looking to have the nine photo roll updated on the website.

I have attached some of the photos we would like to possibly use.

![img_4818](https://user-images.githubusercontent.com/16195489/50773632-53490c00-125f-11e9-9b74-b23be4ee5efa.jpeg)
![cr rafting sept 2018 1](https://user-images.githubusercontent.com/16195489/50773633-53490c00-125f-11e9-9a8a-8b438c1f0d2a.jpg)
![img_5262](https://user-images.githubusercontent.com/16195489/50773635-547a3900-125f-11e9-8703-a0afe9663e9b.jpeg)
![img_20180522_132715](https://user-images.githubusercontent.com/16195489/50773636-547a3900-125f-11e9-8329-4f35ec5476f1.jpeg)
![img_4756](https://user-images.githubusercontent.com/16195489/50773637-547a3900-125f-11e9-87cd-4d21deb0ace5.jpeg)
![adirondacks hiking 1](https://user-images.githubusercontent.com/16195489/50773638-547a3900-125f-11e9-9504-1300725414b2.jpg)
![track 2018 1](https://user-images.githubusercontent.com/16195489/50773639-5512cf80-125f-11e9-8e7d-a6a695215dee.jpg)
![track 2 2018 1](https://user-images.githubusercontent.com/16195489/50773640-5512cf80-125f-11e9-9e3b-fe4f2c459cb6.jpg)
![art drama 2018 2](https://user-images.githubusercontent.com/16195489/50773641-5512cf80-125f-11e9-9983-248d6aaa6fcb.jpg)

**Comment by cbkrol** [comment]
Can you please resize all the images to 3264 x 2448 which is the size of the current photos, this allows the carousel to function smoothly when circling through the pictures.

There are currently 10 pictures, 9 new pictures are submitted here, do you want to keep one from the previous batch or just have 9 total?

**Comment by cbkrol** [comment]
The following video may prove useful for context and technique to resize photos: https://www.youtube.com/watch?v=lMd6nQeryjs

**Comment by JohnnyBigos** [comment]
Thanks.  I will resize them this week.  Thanks for video as well.  9 photos will work.

**Comment by JohnnyBigos** [comment]
Hi, Here are the resized photos.  Let me know if I need to make any changes.  Thanks.

![cr art 2018 1](https://user-images.githubusercontent.com/16195489/51333378-94090800-1a4b-11e9-8487-90964bfd9adc.jpg)
![cr track 2 2018 1](https://user-images.githubusercontent.com/16195489/51333380-94a19e80-1a4b-11e9-8ef6-883b2be38738.jpg)
![cr track 1 1](https://user-images.githubusercontent.com/16195489/51333381-94a19e80-1a4b-11e9-9f27-95b84ea5720c.jpg)
![cr outdoor ed 2018 1](https://user-images.githubusercontent.com/16195489/51333384-94a19e80-1a4b-11e9-82c2-ddb587867234.jpg)
![cr science 2 2018 1](https://user-images.githubusercontent.com/16195489/51333385-94a19e80-1a4b-11e9-9d59-026cc5c9b8ca.jpg)
![cr science 2018 1](https://user-images.githubusercontent.com/16195489/51333386-94a19e80-1a4b-11e9-870a-9049fe8847bb.jpg)
![cr mmun 2018 1](https://user-images.githubusercontent.com/16195489/51333388-953a3500-1a4b-11e9-92b8-09f056d447ad.jpg)
![cr rafting sept 2018 1 1 1](https://user-images.githubusercontent.com/16195489/51333389-953a3500-1a4b-11e9-9a38-50c8e7ebe032.jpg)
![drama 2018 1](https://user-images.githubusercontent.com/16195489/51333390-953a3500-1a4b-11e9-84dd-657bfdf9d2c6.jpg)
